In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("DateFruit_Dataset.csv")

In [4]:
df.head() # 34 features, 1 category

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [5]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [6]:
df.shape

(898, 35)

In [7]:
X = df.drop("Class",axis=1)
y = df["Class"]

In [8]:
df["Class"].unique()

array(['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY'],
      dtype=object)

In [11]:
from sklearn.preprocessing import StandardScaler,LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [13]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state = 42
)

In [14]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [19]:
#ANN

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [17]:
X_train_tensor = torch.tensor(X_train_scaled, dtype = torch.float32)
y_train_tensor = torch.tensor(y_train, dtype = torch.long)

X_test_tensor = torch.tensor(X_test_scaled, dtype = torch.float32)
y_test_tensor = torch.tensor(y_test, dtype = torch.long)

In [21]:
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

In [22]:
train_loader = DataLoader(train_dataset, batch_size =32, shuffle=True)
test_loader =  DataLoader(test_dataset, batch_size =32 )

In [28]:
# Model

class ANN(nn.Module):
  def __init__(self):
    super(ANN,self).__init__()

    self.model = nn.Sequential(
        nn.Linear(X.shape[1], 64),
        nn.ReLU(),

        nn.Linear(64, 64),
        nn.ReLU(),
        nn.Linear(64, 7)
    )
  def forward(self, x):
    return self.model(x)

In [29]:
model = ANN()
# loss, optimizer

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

In [30]:
# training

epochs = 100
for epoch in range (epochs):
  model.train()

  running_loss = 0.0

  for xb,yb in train_loader:
    optimizer.zero_grad()


    outputs = model(xb)
    loss = criterion(outputs, yb)
    loss.backward()
    optimizer.step()

    running_loss += loss

  train_loss = running_loss / len(train_loader)
  print(f" epoch={epoch+1}/{epochs}, loss ={train_loss}")

 epoch=1/100, loss =1.7144097089767456
 epoch=2/100, loss =1.1481820344924927
 epoch=3/100, loss =0.7234905958175659
 epoch=4/100, loss =0.537951648235321
 epoch=5/100, loss =0.43911248445510864
 epoch=6/100, loss =0.3824995160102844
 epoch=7/100, loss =0.34096774458885193
 epoch=8/100, loss =0.29757264256477356
 epoch=9/100, loss =0.27596765756607056
 epoch=10/100, loss =0.2567552924156189
 epoch=11/100, loss =0.2352934330701828
 epoch=12/100, loss =0.22520574927330017
 epoch=13/100, loss =0.2286623865365982
 epoch=14/100, loss =0.21126382052898407
 epoch=15/100, loss =0.19384770095348358
 epoch=16/100, loss =0.1916748285293579
 epoch=17/100, loss =0.18780909478664398
 epoch=18/100, loss =0.1746326982975006
 epoch=19/100, loss =0.16580908000469208
 epoch=20/100, loss =0.15700577199459076
 epoch=21/100, loss =0.15283480286598206
 epoch=22/100, loss =0.15306586027145386
 epoch=23/100, loss =0.14071734249591827
 epoch=24/100, loss =0.14420048892498016
 epoch=25/100, loss =0.13836580514907837
 epoch=26/100, loss =0.13490286469459534
 epoch=27/100, loss =0.1308024823665619
 epoch=28/100, loss =0.13180223107337952
 epoch=29/100, loss =0.13065125048160553
 epoch=30/100, loss =0.12593230605125427
 epoch=31/100, loss =0.12133374065160751
 epoch=32/100, loss =0.11009962856769562
 epoch=33/100, loss =0.1115485355257988
 epoch=34/100, loss =0.11223870515823364
 epoch=35/100, loss =0.1109103411436081
 epoch=36/100, loss =0.10523083806037903
 epoch=37/100, loss =0.1007668673992157
 epoch=38/100, loss =0.09930864721536636
 epoch=39/100, loss =0.09652473777532578
 epoch=40/100, loss =0.09831251204013824
 epoch=41/100, loss =0.09056401252746582
 epoch=42/100, loss =0.09033852815628052
 epoch=43/100, loss =0.0873103141784668
 epoch=44/100, loss =0.08385710418224335
 epoch=45/100, loss =0.09400852769613266
 epoch=46/100, loss =0.08623460680246353
 epoch=47/100, loss =0.08779878169298172
 epoch=48/100, loss =0.0818069577217102
 epoch=49/100, loss =0.08479820936918259
 epoch=50/100, loss =0.07198760658502579
 epoch=51/100, loss =0.07453729957342148
 epoch=52/100, loss =0.06982421875
 epoch=53/100, loss =0.08157121390104294
 epoch=54/100, loss =0.06698703020811081
 epoch=55/100, loss =0.06784944236278534
 epoch=56/100, loss =0.06818005442619324
 epoch=57/100, loss =0.06945697218179703
 epoch=58/100, loss =0.06096281111240387
 epoch=59/100, loss =0.059369541704654694
 epoch=60/100, loss =0.06155791133642197
 epoch=61/100, loss =0.0646359995007515
 epoch=62/100, loss =0.06134527176618576
 epoch=63/100, loss =0.054692622274160385
 epoch=64/100, loss =0.06158377230167389
 epoch=65/100, loss =0.055946215987205505
 epoch=66/100, loss =0.05433410033583641
 epoch=67/100, loss =0.055826716125011444
 epoch=68/100, loss =0.05083665996789932
 epoch=69/100, loss =0.048352375626564026
 epoch=70/100, loss =0.0475442111492157
 epoch=71/100, loss =0.05075594037771225
 epoch=72/100, loss =0.05118941143155098
 epoch=73/100, loss =0.04629889130592346
 epoch=74/100, loss =0.04411628097295761
 epoch=75/100, loss =0.04373277723789215
 epoch=76/100, loss =0.04266049340367317
 epoch=77/100, loss =0.04346119239926338
 epoch=78/100, loss =0.03982740268111229
 epoch=79/100, loss =0.03972962498664856
 epoch=80/100, loss =0.03763742372393608
 epoch=81/100, loss =0.03804672881960869
 epoch=82/100, loss =0.03881990164518356
 epoch=83/100, loss =0.0353197380900383
 epoch=84/100, loss =0.034826282411813736
 epoch=85/100, loss =0.037644945085048676
 epoch=86/100, loss =0.03305569291114807
 epoch=87/100, loss =0.035850342363119125
 epoch=88/100, loss =0.03153027594089508
 epoch=89/100, loss =0.032249365001916885
 epoch=90/100, loss =0.03401373699307442
 epoch=91/100, loss =0.030957097187638283
 epoch=92/100, loss =0.02907070890069008
 epoch=93/100, loss =0.03259861841797829
 epoch=94/100, loss =0.03249605745077133
 epoch=95/100, loss =0.03058781661093235
 epoch=96/100, loss =0.02545962855219841
 epoch=97/100, loss =0.026151670143008232
 epoch=98/100, loss =0.028472259640693665
 epoch=99/100, loss =0.02641979418694973
 epoch=100/100, loss =0.026107709854841232

In [33]:
# Evaluation

model.eval()
total = 0
correct = 0

with torch.no_grad():
  for xb, yb in test_loader:
    outputs = model(xb)
    _,predicted = torch.max(outputs, 1)

    correct += (predicted == yb).sum().item()
    total += yb.size(0) # actual samples in each batch

print("accuracy: ", correct / total * 100)

accuracy:  95.0

In [35]:
y_test.shape

(180,)